variant_name: dqposemindirect
batch_size: 64
epochs: 50
past_length: 10
future_length: 10
eval_interval: 1
lr: 3.e-4
weight_decay: 1.e-5
scale: 1000
milestone: [5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 35, 37, 40, 42, 45, 47, 50]
gamma: 0.88
key_point: 25
n_layer: 4
e_dim: 84
h_dim: 72
aug: false
n_hop: -1
norm: true
position_loss_weight: 1.0
aux_loss: true
aux_loss_weight: 1.0
loss_type: [L2, L1]
pose_loss: true
pose_loss_start_epoch: 11
pose_loss_weight: 0.005
pose_velocity_loss_weight: 0.005
pose_joint_weighting: none
pose_rot_weight: 1.0
pose_trans_weight: 1.0
dqpose_reference_joint: 8
dqpose_decode_mode: direct
dqpose_block_mode: joint
fk: 1
keep: 5
early_abort_epoch: 10
early_abort_avg: 26.7
early_abort_400: 46.0
early_stop_start_epoch: 12
early_stop_patience: 5
early_stop_min_delta: 0.05
